#!/bin/sh

# Copyright (C) 2010 The Android Open Source Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is generated by device/common/generate-blob-scripts.sh - DO NOT EDIT

DEVICE=a800
MANUFACTURER=lenovo

mkdir -p ../../../vendor/$MANUFACTURER/$DEVICE/proprietary
adb pull /system/vendor/bin/pvrsrvinit ../../../vendor/$MANUFACTURER/$DEVICE/proprietary/pvrsrvinit
adb pull /system/vendor/bin/pvrsrvctl ../../../vendor/$MANUFACTURER/$DEVICE/proprietary/pvrsrvctl
adb pull /system/vendor/bin/rc.fac ../../../vendor/$MANUFACTURER/$DEVICE/proprietary/rc.fac
chmod 755 ../../../vendor/$MANUFACTURER/$DEVICE/proprietary/pvrsrvinit
chmod 755 ../../../vendor/$MANUFACTURER/$DEVICE/proprietary/pvrsrvctl
adb pull /system/vendor/lib/libBLPP.so ../../../vendor/$MANUFACTURER/$DEVICE/proprietary/libBLPP.so
adb pull /system/vendor/lib/libglslcompiler.so ../../../vendor/$MANUFACTURER/$DEVICE/proprietary/libglslcompiler.so
adb pull /system/vendor/lib/libIMGegl.so ../../../vendor/$MANUFACTURER/$DEVICE/proprietary/libIMGegl.so
adb pull /system/vendor/lib/libpvr2d.so ../../../vendor/$MANUFACTURER/$DEVICE/proprietary/libpvr2d.so
adb pull /system/vendor/lib/libpvrANDROID_WSEGL.so ../../../vendor/$MANUFACTURER/$DEVICE/proprietary/libpvrANDROID_WSEGL.so
adb pull /system/vendor/lib/libPVRScopeServices.so ../../../vendor/$MANUFACTURER/$DEVICE/proprietary/libPVRScopeServices.so
adb pull /system/vendor/lib/libsrv_init.so ../../../vendor/$MANUFACTURER/$DEVICE/proprietary/libsrv_init.so
adb pull /system/vendor/lib/libsrv_um.so ../../../vendor/$MANUFACTURER/$DEVICE/proprietary/libsrv_um.so
adb pull /system/vendor/lib/libusc.so ../../../vendor/$MANUFACTURER/$DEVICE/proprietary/libusc.so
adb pull /system/vendor/lib/libwvdrm_L3.so ../../../vendor/$MANUFACTURER/$DEVICE/proprietary/libwvdrm_L3.so
adb pull /system/vendor/lib/libwvm.so ../../../vendor/$MANUFACTURER/$DEVICE/proprietary/libwvm.so
adb pull /system/vendor/lib/libWVStreamControlAPI_L3.so ../../../vendor/$MANUFACTURER/$DEVICE/proprietary/libWVStreamControlAPI_L3.so
adb pull /system/vendor/lib/drm/libdrmwvmplugin.so ../../../vendor/$MANUFACTURER/$DEVICE/proprietary/libdrmwvmplugin.so
adb pull /system/vendor/lib/egl/libEGL_mtk.so ../../../vendor/$MANUFACTURER/$DEVICE/proprietary/libEGL_mtk.so
adb pull /system/vendor/lib/egl/libGLESv1_CM_mtk.so ../../../vendor/$MANUFACTURER/$DEVICE/proprietary/libGLESv1_CM_mtk.so
adb pull /system/vendor/lib/egl/libGLESv2_mtk.so ../../../vendor/$MANUFACTURER/$DEVICE/proprietary/libGLESv2_mtk.so
adb pull /system/vendor/lib/hw/gralloc.mt6577.so ../../../vendor/$MANUFACTURER/$DEVICE/proprietary/gralloc.mt6577.so
adb pull /system/etc/firmware/modem.img ../../../vendor/$MANUFACTURER/$DEVICE/proprietary/firmware/modem.img
adb pull /system/etc/firmware/mt6628_fm_rom.bin ../../../vendor/$MANUFACTURER/$DEVICE/proprietary/firmware/mt6628_fm_rom.bin
adb pull /system/etc/firmware/mt6628_fm_v1_coeff.bin ../../../vendor/$MANUFACTURER/$DEVICE/proprietary/firmware/mt6628_fm_v1_coeff.bin
adb pull /system/etc/firmware/mt6628_fm_v1_patch.bin ../../../vendor/$MANUFACTURER/$DEVICE/proprietary/firmware/mt6628_fm_v1_patch.bin
adb pull /system/etc/firmware/mt6628_fm_v2_coeff.bin ../../../vendor/$MANUFACTURER/$DEVICE/proprietary/firmware/mt6628_fm_v2_coeff.bin
adb pull /system/etc/firmware/mt6628_fm_v2_patch.bin ../../../vendor/$MANUFACTURER/$DEVICE/proprietary/firmware/mt6628_fm_v2_patch.bin
adb pull /system/etc/firmware/mt6628_fm_v3_coeff.bin ../../../vendor/$MANUFACTURER/$DEVICE/proprietary/firmware/mt6628_fm_v3_coeff.bin
adb pull /system/etc/firmware/mt6628_fm_v3_patch.bin ../../../vendor/$MANUFACTURER/$DEVICE/proprietary/firmware/mt6628_fm_v3_patch.bin
adb pull /system/etc/firmware/mt6628_fm_v4_coeff.bin ../../../vendor/$MANUFACTURER/$DEVICE/proprietary/firmware/mt6628_fm_v4_coeff.bin
adb pull /system/etc/firmware/mt6628_fm_v4_patch.bin ../../../vendor/$MANUFACTURER/$DEVICE/proprietary/firmware/mt6628_fm_v4_patch.bin
adb pull /system/etc/firmware/mt6628_fm_v5_coeff.bin ../../../vendor/$MANUFACTURER/$DEVICE/proprietary/firmware/mt6628_fm_v5_coeff.bin
adb pull /system/etc/firmware/mt6628_fm_v5_patch.bin ../../../vendor/$MANUFACTURER/$DEVICE/proprietary/firmware/mt6628_fm_v5_patch.bin
adb pull /system/etc/firmware/mt6628_patch_e1_hdr.bin ../../../vendor/$MANUFACTURER/$DEVICE/proprietary/firmware/mt6628_patch_e1_hdr.bin
adb pull /system/etc/firmware/mt6628_patch_e2_hdr.bin ../../../vendor/$MANUFACTURER/$DEVICE/proprietary/firmware/mt6628_patch_e2_hdr.bin

(cat << EOF) | sed s/__DEVICE__/$DEVICE/g | sed s/__MANUFACTURER__/$MANUFACTURER/g > ../../../vendor/$MANUFACTURER/$DEVICE/device-vendor-blobs.mk
# Copyright (C) 2010 The Android Open Source Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is generated by device/__MANUFACTURER__/__DEVICE__/extract-files.sh - DO NOT EDIT

# Prebuilt libraries that are needed to build open-source libraries

# All the blobs necessary for a800
PRODUCT_COPY_FILES := \\
    vendor/lenovo/a800/proprietary/pvrsrvinit:system/bin/pvrsrvinit 
PRODUCT_COPY_FILES += \\
    vendor/__MANUFACTURER__/__DEVICE__/proprietary/pvrsrvctl:system/bin/pvrsrvctl \\
    vendor/__MANUFACTURER__/__DEVICE__/proprietary/rc.fac:system/bin/rc.fac \\
    vendor/__MANUFACTURER__/__DEVICE__/proprietary/libBLPP.so:system/lib/libBLPP.so \\
    vendor/__MANUFACTURER__/__DEVICE__/proprietary/libglslcompiler.so:system/lib/libglslcompiler.so \\
    vendor/__MANUFACTURER__/__DEVICE__/proprietary/libIMGegl.so:system/lib/libIMGegl.so \\
    vendor/__MANUFACTURER__/__DEVICE__/proprietary/libpvr2d.so:system/lib/libpvr2d.so \\
    vendor/__MANUFACTURER__/__DEVICE__/proprietary/libpvrANDROID_WSEGL.so:system/lib/libpvrANDROID_WSEGL.so \\
    vendor/__MANUFACTURER__/__DEVICE__/proprietary/libPVRScopeServices.so:system/lib/libPVRScopeServices.so \\
    vendor/__MANUFACTURER__/__DEVICE__/proprietary/libsrv_init.so:system/lib/libsrv_init.so \\
    vendor/__MANUFACTURER__/__DEVICE__/proprietary/libsrv_um.so:system/lib/libsrv_um.so \\
    vendor/__MANUFACTURER__/__DEVICE__/proprietary/libusc.so:system/lib/libusc.so \\
    vendor/__MANUFACTURER__/__DEVICE__/proprietary/libwvm.so:system/lib/libwvm.so \\
    vendor/__MANUFACTURER__/__DEVICE__/proprietary/libwvdrm_L3.so:system/lib/libwvdrm_L3.so \\
    vendor/__MANUFACTURER__/__DEVICE__/proprietary/libwvm.so:system/lib/libwvm.so \\
    vendor/__MANUFACTURER__/__DEVICE__/proprietary/libWVStreamControlAPI_L3.so:system/lib/libWVStreamControlAPI_L3.so \\
    vendor/__MANUFACTURER__/__DEVICE__/proprietary/libdrmwvmplugin.so:system/lib/drm/libdrmwvmplugin.so \\
    vendor/__MANUFACTURER__/__DEVICE__/proprietary/libEGL_mtk.so:system/lib/egl/libEGL_mtk.so \\
    vendor/__MANUFACTURER__/__DEVICE__/proprietary/libGLESv1_CM_mtk.so:system/lib/egl/libGLESv1_CM_mtk.so \\
    vendor/__MANUFACTURER__/__DEVICE__/proprietary/libGLESv2_mtk.so:system/lib/egl/libGLESv2_mtk.so \\
    vendor/__MANUFACTURER__/__DEVICE__/proprietary/gralloc.mt6577.so:system/lib/hw/gralloc.mt6577.so \\
    vendor/__MANUFACTURER__/__DEVICE__/proprietary/firmware/modem.img:system/etc/firmware/modem.img \\
    vendor/__MANUFACTURER__/__DEVICE__/proprietary/firmware/mt6628_fm_rom.bin:system/etc/firmware/mt6628_fm_rom.bin \\
    vendor/__MANUFACTURER__/__DEVICE__/proprietary/firmware/mt6628_fm_v1_coeff.bin:system/etc/firmware/mt6628_fm_v1_coeff.bin \\
    vendor/__MANUFACTURER__/__DEVICE__/proprietary/firmware/mt6628_fm_v2_coeff.bin:system/etc/firmware/mt6628_fm_v2_coeff.bin \\
    vendor/__MANUFACTURER__/__DEVICE__/proprietary/firmware/mt6628_fm_v3_coeff.bin:system/etc/firmware/mt6628_fm_v3_coeff.bin \\
    vendor/__MANUFACTURER__/__DEVICE__/proprietary/firmware/mt6628_fm_v4_coeff.bin:system/etc/firmware/mt6628_fm_v4_coeff.bin \\
    vendor/__MANUFACTURER__/__DEVICE__/proprietary/firmware/mt6628_fm_v5_coeff.bin:system/etc/firmware/mt6628_fm_v5_coeff.bin \\
    vendor/__MANUFACTURER__/__DEVICE__/proprietary/firmware/mt6628_fm_v1_patch.bin:system/etc/firmware/mt6628_fm_v1_patch.bin \\
    vendor/__MANUFACTURER__/__DEVICE__/proprietary/firmware/mt6628_fm_v2_patch.bin:system/etc/firmware/mt6628_fm_v2_patch.bin \\
    vendor/__MANUFACTURER__/__DEVICE__/proprietary/firmware/mt6628_fm_v3_patch.bin:system/etc/firmware/mt6628_fm_v3_patch.bin \\
    vendor/__MANUFACTURER__/__DEVICE__/proprietary/firmware/mt6628_fm_v4_patch.bin:system/etc/firmware/mt6628_fm_v4_patch.bin \\
    vendor/__MANUFACTURER__/__DEVICE__/proprietary/firmware/mt6628_fm_v5_patch.bin:system/etc/firmware/mt6628_fm_v5_patch.bin \\
    vendor/__MANUFACTURER__/__DEVICE__/proprietary/firmware/mt6628_patch_e1_hdr.bin:system/etc/firmware/mt6628_patch_e1_hdr.bin \\
    vendor/__MANUFACTURER__/__DEVICE__/proprietary/firmware/mt6628_patch_e2_hdr.bin:system/etc/firmware/mt6628_patch_e2_hdr.bin 

EOF

(cat << EOF) | sed s/__DEVICE__/$DEVICE/g | sed s/__MANUFACTURER__/$MANUFACTURER/g > ../../../vendor/$MANUFACTURER/$DEVICE/proprietary/Android.mk
# Copyright (C) 2011 The Android Open Source Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is generated by device/__MANUFACTURER__/__DEVICE__/extract-files.sh - DO NOT EDIT

ifeq (\$(TARGET_DEVICE),a800)
LOCAL_PATH:=\$(call my-dir)

endif

EOF

./setup-makefiles.sh
